name: Docs testing

on:
  workflow_trigger:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Fix dumb git issue
        run: |
          git config --global --add safe.directory ${PWD}
      - name: Build
        run: make docs
      - uses: actions/upload-artifact@v7
        name: Upload Documentation As Artifact
        with:
          name: '${{ github.sha }}-docs'
          path: '${{ github.workspace }}/build/docs/out'
          retention-days: 7
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: monetr.app
          folder: build/docs/out
