name: Docs

on:
  workflow_dispatch:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Fix dumb git issue
        run: |
          git config --global --add safe.directory ${PWD}
      - name: Build
        run: make docs
      - uses: actions/upload-artifact@v7
        name: Upload Documentation As Artifact
        with:
          name: '${{ github.sha }}-docs'
          path: '${{ github.workspace }}/build/docs/out'
          retention-days: 7
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs/out

  # Deployment job
  deploy:
    name: Deploy github pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
